# Generated by Django 3.0.4 on 2020-03-17 21:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification_app', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=700)),
                ('video_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification_app.User')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=200)),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_app.Comment')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentification_app.User')),
                ('video_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_app.Video')),
            ],
        ),
    ]
