# Generated by Django 3.0.4 on 2020-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_reference',
            field=models.UUIDField(unique=True),
        ),
    ]
