# Generated by Django 3.0.4 on 2020-03-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_initial_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='video_app.Comment'),
        ),
    ]
