# Generated by Django 3.0.4 on 2020-03-17 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('activation_token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
